In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))  
from theODDS import p_helpers as p
from KALSHI import k_helpers as k 
import config

# Testing functions: 

Make a PoC file - no threading, run as simple as possible to show this is possible.

In [2]:
sports = config.SPORTS

sports

['basketball_ncaab',
 'soccer_mexico_ligamx',
 'soccer_argentina_primera_division',
 'soccer_brazil_campeonato']

## Pinnacle Odds Fn

In [3]:
x = p.pinnacle_odds(sports, hrs = 70, live = False)
display(x)

Requests used: 89 / 411 remaining

Requests used: 90 / 410 remaining

Requests used: 91 / 409 remaining

Requests used: 92 / 408 remaining

,sport,event_id,home,away,commence,bookmaker,outcome,decimal_odds,implied_prob,vig_pct,fair_prob
0,basketball_ncaab,dcc2e1aabfce3314a2ea90e566839129,Howard Bison,UMBC Retrievers,2026-03-17 18:40:00-04:00,pinnacle,Howard Bison,1.96,0.5102,2.834,0.4961
1,basketball_ncaab,dcc2e1aabfce3314a2ea90e566839129,Howard Bison,UMBC Retrievers,2026-03-17 18:40:00-04:00,pinnacle,UMBC Retrievers,1.93,0.5181,2.834,0.5039
2,basketball_ncaab,83db61d68c8c62ef872b1eee299ab99e,Texas Longhorns,NC State Wolfpack,2026-03-17 21:15:00-04:00,pinnacle,NC State Wolfpack,1.94,0.5155,3.093,0.5000
3,basketball_ncaab,83db61d68c8c62ef872b1eee299ab99e,Texas Longhorns,NC State Wolfpack,2026-03-17 21:15:00-04:00,pinnacle,Texas Longhorns,1.94,0.5155,3.093,0.5000
4,basketball_ncaab,2e509835ca6e5a0564e5e470fca0ba82,Lehigh Mountain Hawks,Prairie View Panthers,2026-03-18 18:40:00-04:00,pinnacle,Lehigh Mountain Hawks,1.61,0.6211,3.095,0.6025
...,...,...,...,...,...,...,...,...,...,...,...
60,soccer_brazil_campeonato,d54e99446ff46e433be3a908632eacfa,Grêmio,Vitoria,2026-03-19 18:00:00-04:00,pinnacle,Vitoria,4.44,0.2252,5.032,0.2144
61,soccer_brazil_campeonato,d54e99446ff46e433be3a908632eacfa,Grêmio,Vitoria,2026-03-19 18:00:00-04:00,pinnacle,Draw,3.71,0.2695,5.032,0.2566
62,soccer_brazil_campeonato,f61a9e12904cb3e6e379e1c4a6c376c9,Flamengo,Remo,2026-03-19 19:00:00-04:00,pinnacle,Flamengo,1.18,0.8475,5.090,0.8064
63,soccer_brazil_campeonato,f61a9e12904cb3e6e379e1c4a6c376c9,Flamengo,Remo,2026-03-19 19:00:00-04:00,pinnacle,Remo,15.22,0.0657,5.090,0.0625
64,soccer_brazil_campeonato,f61a9e12904cb3e6e379e1c4a6c376c9,Flamengo,Remo,2026-03-19 19:00:00-04:00,pinnacle,Draw,7.26,0.1377,5.090,0.1311

## Kalshi Fn's

In [4]:
x2 = k.kalshi_odds(x)
display(x2[x2['signal'] == True])

,sport,event_id,home,away,commence,outcome,fair_prob,k_event_ticker,k_ticker,yes_bid,yes_ask,no_bid,no_ask,volume,OI,match_score,signal
1,basketball_ncaab,174de90eaae141a31d206e3c911cfb4e,SMU Mustangs,Miami (OH) RedHawks,2026-03-18 21:15:00-04:00,SMU Mustangs,0.7313,KXNCAAMBGAME-26MAR18SHSUUNM,KXNCAAMBGAME-26MAR18SHSUUNM-SHSU,0.14,0.15,0.85,0.86,1341.00,1341.00,0.609,True
4,soccer_mexico_ligamx,21cabf8da8593cdc460b647260680406,Guadalajara,León,2026-03-18 22:07:00-04:00,Draw,0.1942,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
8,soccer_brazil_campeonato,4be96369cbf700bba9e226c378e45186,Palmeiras,Botafogo,2026-03-18 18:00:00-04:00,Draw,0.2238,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
12,soccer_brazil_campeonato,5ea12305256351febc4947e3e97e2c20,Bahia,Bragantino-SP,2026-03-18 18:00:00-04:00,Draw,0.2701,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
17,soccer_brazil_campeonato,642269880b4f98a6d95ea679a87c66a0,Vasco da Gama,Fluminense,2026-03-18 20:30:00-04:00,Draw,0.2948,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
19,soccer_argentina_primera_division,7bc350a9d4066e9b731418c9f332faae,Central Córdoba,Deportivo Riestra,2026-03-17 20:15:00-04:00,Draw,0.3793,KXARGPREMDIVGAME-26MAR17GEMELP,KXARGPREMDIVGAME-26MAR17GEMELP-TIE,0.32,0.34,0.66,0.68,0.00,0.00,1.000,True
27,soccer_brazil_campeonato,9a11fcf06f58e6472bf2303956d228b7,Atletico Paranaense,Cruzeiro,2026-03-18 18:30:00-04:00,Draw,0.2917,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
30,soccer_brazil_campeonato,be55b00873c62543c2c123288d664255,Santos,Internacional,2026-03-18 20:30:00-04:00,Draw,0.3067,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
33,soccer_brazil_campeonato,c376463751f28ab5ad1827debc73a3f1,Atletico Mineiro,Sao Paulo,2026-03-18 19:00:00-04:00,Draw,0.3162,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
36,soccer_brazil_campeonato,c94b10894a554309f91d499eb14a405e,Mirassol,Coritiba,2026-03-18 19:00:00-04:00,Draw,0.2699,KXLIGAMXGAME-26MAR18CDGLEO,KXLIGAMXGAME-26MAR18CDGLEO-TIE,0.17,0.18,0.82,0.83,797.00,480.00,1.000,True
42,basketball_ncaab,e1392b7328ef7749e85605ddae5ab7cf,Michigan St Spartans,North Dakota St Bison,2026-03-19 16:05:59-04:00,North Dakota St Bison,0.0928,KXNCAAMBGAME-26MAR19NDSUMSU,KXNCAAMBGAME-26MAR19NDSUMSU-NDSU,0.07,0.08,0.92,0.93,72186.00,67838.00,0.811,True