In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))  
from theODDS import p_helpers as p
from KALSHI import k_helpers as k 
import config

# Testing functions: 

Make a PoC file - no threading, run as simple as possible to show this is possible.

In [2]:
sports = config.SPORTS

sports

['basketball_ncaab',
 'soccer_mexico_ligamx',
 'soccer_argentina_primera_division',
 'soccer_brazil_campeonato']

## Pinnacle Odds Fn

In [3]:
x = p.pinnacle_odds(sports, hrs = 70, live = False)
display(x)

Requests used: 2 / 498 remaining

Requests used: 3 / 497 remaining

Requests used: 4 / 496 remaining

Requests used: 5 / 495 remaining

,sport,event_id,home,away,commence,bookmaker,outcome,decimal_odds,implied_prob,vig_pct,fair_prob
0,basketball_ncaab,0b1d66a8749e69eed9aef423368342da,Baylor Bears,Oklahoma Sooners,2026-04-04 13:30:00-04:00,pinnacle,Baylor Bears,1.99,0.5025,4.015,0.4831
1,basketball_ncaab,0b1d66a8749e69eed9aef423368342da,Baylor Bears,Oklahoma Sooners,2026-04-04 13:30:00-04:00,pinnacle,Oklahoma Sooners,1.86,0.5376,4.015,0.5169
2,basketball_ncaab,cb594dfdc3259e7a3376bc1167311085,Creighton Bluejays,West Virginia Mountaineers,2026-04-04 16:00:00-04:00,pinnacle,Creighton Bluejays,1.97,0.5076,3.953,0.4883
3,basketball_ncaab,cb594dfdc3259e7a3376bc1167311085,Creighton Bluejays,West Virginia Mountaineers,2026-04-04 16:00:00-04:00,pinnacle,West Virginia Mountaineers,1.88,0.5319,3.953,0.5117
4,basketball_ncaab,107fec52e1d9d6f2f6e74f47eb1d520b,UConn Huskies,Illinois Fighting Illini,2026-04-04 18:09:00-04:00,pinnacle,Illinois Fighting Illini,1.79,0.5587,3.036,0.5422
...,...,...,...,...,...,...,...,...,...,...,...
84,soccer_brazil_campeonato,effd55368995e78965f7ad0cef4df5ef,Mirassol,Bragantino-SP,2026-04-05 19:00:00-04:00,pinnacle,Mirassol,2.23,0.4484,4.816,0.4278
85,soccer_brazil_campeonato,effd55368995e78965f7ad0cef4df5ef,Mirassol,Bragantino-SP,2026-04-05 19:00:00-04:00,pinnacle,Draw,3.31,0.3021,4.816,0.2882
86,soccer_brazil_campeonato,ce3f4f4b288df6222ac4e669d521f836,Grêmio,Remo,2026-04-05 19:30:00-04:00,pinnacle,Grêmio,1.50,0.6667,5.151,0.6340
87,soccer_brazil_campeonato,ce3f4f4b288df6222ac4e669d521f836,Grêmio,Remo,2026-04-05 19:30:00-04:00,pinnacle,Remo,6.59,0.1517,5.151,0.1443
88,soccer_brazil_campeonato,ce3f4f4b288df6222ac4e669d521f836,Grêmio,Remo,2026-04-05 19:30:00-04:00,pinnacle,Draw,4.29,0.2331,5.151,0.2217

## Kalshi Fn's

In [4]:
x2 = k.kalshi_odds(x)
display(x2)
# display(x2[x2['signal'] == True])

,sport,event_id,home,away,commence,outcome,fair_prob,k_event_ticker,k_ticker,yes_bid,yes_ask,no_bid,no_ask,volume,OI,match_score,signal
0,basketball_ncaab,0b1d66a8749e69eed9aef423368342da,Baylor Bears,Oklahoma Sooners,2026-04-04 13:30:00-04:00,Baylor Bears,0.4831,KXNCAAMBGAME-26APR04OKLABAY,KXNCAAMBGAME-26APR04OKLABAY-BAY,0.46,0.48,0.52,0.54,4439.00,1186.00,0.667,False
1,basketball_ncaab,0b1d66a8749e69eed9aef423368342da,Baylor Bears,Oklahoma Sooners,2026-04-04 13:30:00-04:00,Oklahoma Sooners,0.5169,KXNCAAMBGAME-26APR04OKLABAY,KXNCAAMBGAME-26APR04OKLABAY-OKLA,0.51,0.53,0.47,0.49,8539.00,6128.00,0.667,False
2,soccer_argentina_primera_division,0e02fd8dae97049ba1e160034d58b2bc,Independiente,Racing Club,2026-04-04 16:30:00-04:00,Independiente,0.3651,KXARGPREMDIVGAME-26APR04CAIRAC,KXARGPREMDIVGAME-26APR04CAIRAC-CAI,0.33,0.39,0.61,0.67,2.00,2.00,0.703,False
3,soccer_argentina_primera_division,0e02fd8dae97049ba1e160034d58b2bc,Independiente,Racing Club,2026-04-04 16:30:00-04:00,Draw,0.3074,KXLIGAMXGAME-26APR04CRAPAC,KXLIGAMXGAME-26APR04CRAPAC-TIE,0.21,0.23,0.77,0.79,142.00,142.00,1.000,True
4,soccer_argentina_primera_division,15a6fdfd62494c108a66643fcc76c322,Union Santa Fe,Deportivo Riestra,2026-04-03 16:15:00-04:00,Union Santa Fe,0.5084,KXARGPREMDIVGAME-26APR03UNIRIE,KXARGPREMDIVGAME-26APR03UNIRIE-UNI,0.51,0.52,0.48,0.49,3449.00,3448.00,1.000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,soccer_mexico_ligamx,eacf84dc6ccbd4eaabb7c9df34e606d8,Puebla,FC Juárez,2026-04-03 21:00:00-04:00,Puebla,0.3523,KXLIGAMXGAME-26APR03PUEJUA,KXLIGAMXGAME-26APR03PUEJUA-PUE,0.35,0.36,0.64,0.65,1698.00,1667.00,1.000,False
76,soccer_mexico_ligamx,eacf84dc6ccbd4eaabb7c9df34e606d8,Puebla,FC Juárez,2026-04-03 21:00:00-04:00,Draw,0.2722,KXLIGAMXGAME-26APR03TIJTIG,KXLIGAMXGAME-26APR03TIJTIG-TIE,0.26,0.27,0.73,0.74,1294.00,1294.00,1.000,False
77,soccer_brazil_campeonato,effd55368995e78965f7ad0cef4df5ef,Mirassol,Bragantino-SP,2026-04-05 19:00:00-04:00,Bragantino-SP,0.2839,KXBRASILEIROGAME-26APR05MIRRBB,KXBRASILEIROGAME-26APR05MIRRBB-RBB,0.26,0.30,0.70,0.74,0.00,0.00,0.870,False
78,soccer_brazil_campeonato,effd55368995e78965f7ad0cef4df5ef,Mirassol,Bragantino-SP,2026-04-05 19:00:00-04:00,Mirassol,0.4278,KXBRASILEIROGAME-26APR05MIRRBB,KXBRASILEIROGAME-26APR05MIRRBB-MIR,0.41,0.46,0.54,0.59,69.00,69.00,1.000,False
79,soccer_brazil_campeonato,effd55368995e78965f7ad0cef4df5ef,Mirassol,Bragantino-SP,2026-04-05 19:00:00-04:00,Draw,0.2882,KXLIGAMXGAME-26APR05CDGPUM,KXLIGAMXGAME-26APR05CDGPUM-TIE,0.20,0.22,0.78,0.80,967.00,967.00,1.000,True