In [4]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))  
from theODDS import p_helpers as p
from KALSHI import k_helpers as k 
import config

# Testing functions: 

Make a PoC file - no threading, run as simple as possible to show this is possible.

In [5]:
sports = config.SPORTS

sports

['basketball_ncaab']

## Pinnacle Odds Fn

In [6]:
x = p.pinnacle_odds(sports, hrs = 70, live = False)
display(x)

Requests used: 71 / 429 remaining

,sport,event_id,home,away,commence,bookmaker,outcome,decimal_odds,implied_prob,vig_pct,fair_prob
0,basketball_ncaab,dcc2e1aabfce3314a2ea90e566839129,Howard Bison,UMBC Retrievers,2026-03-17 18:40:00-04:00,pinnacle,Howard Bison,1.99,0.5025,2.883,0.4884
1,basketball_ncaab,dcc2e1aabfce3314a2ea90e566839129,Howard Bison,UMBC Retrievers,2026-03-17 18:40:00-04:00,pinnacle,UMBC Retrievers,1.90,0.5263,2.883,0.5116
2,basketball_ncaab,83db61d68c8c62ef872b1eee299ab99e,Texas Longhorns,NC State Wolfpack,2026-03-17 21:15:00-04:00,pinnacle,NC State Wolfpack,1.92,0.5208,3.897,0.5013
3,basketball_ncaab,83db61d68c8c62ef872b1eee299ab99e,Texas Longhorns,NC State Wolfpack,2026-03-17 21:15:00-04:00,pinnacle,Texas Longhorns,1.93,0.5181,3.897,0.4987
4,basketball_ncaab,2e509835ca6e5a0564e5e470fca0ba82,Lehigh Mountain Hawks,Prairie View Panthers,2026-03-18 18:40:00-04:00,pinnacle,Lehigh Mountain Hawks,1.63,0.6135,2.843,0.5965
5,basketball_ncaab,2e509835ca6e5a0564e5e470fca0ba82,Lehigh Mountain Hawks,Prairie View Panthers,2026-03-18 18:40:00-04:00,pinnacle,Prairie View Panthers,2.41,0.4149,2.843,0.4035
6,basketball_ncaab,174de90eaae141a31d206e3c911cfb4e,SMU Mustangs,Miami (OH) RedHawks,2026-03-18 21:15:00-04:00,pinnacle,Miami (OH) RedHawks,3.62,0.2762,2.812,0.2687
7,basketball_ncaab,174de90eaae141a31d206e3c911cfb4e,SMU Mustangs,Miami (OH) RedHawks,2026-03-18 21:15:00-04:00,pinnacle,SMU Mustangs,1.33,0.7519,2.812,0.7313
8,basketball_ncaab,ffe3c0fdb29507477476637fcbc795cf,Ohio State Buckeyes,TCU Horned Frogs,2026-03-19 12:15:00-04:00,pinnacle,Ohio State Buckeyes,1.70,0.5882,2.876,0.5718
9,basketball_ncaab,ffe3c0fdb29507477476637fcbc795cf,Ohio State Buckeyes,TCU Horned Frogs,2026-03-19 12:15:00-04:00,pinnacle,TCU Horned Frogs,2.27,0.4405,2.876,0.4282
10,basketball_ncaab,df39114e937cbae1271ab4267afae55d,Nebraska Cornhuskers,Troy Trojans,2026-03-19 12:40:00-04:00,pinnacle,Nebraska Cornhuskers,1.11,0.9009,3.010,0.8746
11,basketball_ncaab,df39114e937cbae1271ab4267afae55d,Nebraska Cornhuskers,Troy Trojans,2026-03-19 12:40:00-04:00,pinnacle,Troy Trojans,7.74,0.1292,3.010,0.1254
12,basketball_ncaab,f7b3bd4eccbe852bda4d3446090eedad,Louisville Cardinals,South Florida Bulls,2026-03-19 13:30:00-04:00,pinnacle,Louisville Cardinals,1.48,0.6757,2.903,0.6566
13,basketball_ncaab,f7b3bd4eccbe852bda4d3446090eedad,Louisville Cardinals,South Florida Bulls,2026-03-19 13:30:00-04:00,pinnacle,South Florida Bulls,2.83,0.3534,2.903,0.3434
14,basketball_ncaab,5ee2959a7e3a36958ec1948e2911d209,Wisconsin Badgers,High Point Panthers,2026-03-19 13:50:00-04:00,pinnacle,High Point Panthers,4.75,0.2105,3.020,0.2044
15,basketball_ncaab,5ee2959a7e3a36958ec1948e2911d209,Wisconsin Badgers,High Point Panthers,2026-03-19 13:50:00-04:00,pinnacle,Wisconsin Badgers,1.22,0.8197,3.020,0.7956
16,basketball_ncaab,65e6158d4f85c02c5909322558981536,Duke Blue Devils,Siena Saints,2026-03-19 14:50:50-04:00,pinnacle,Duke Blue Devils,1.01,0.9901,1.734,0.9732
17,basketball_ncaab,65e6158d4f85c02c5909322558981536,Duke Blue Devils,Siena Saints,2026-03-19 14:50:50-04:00,pinnacle,Siena Saints,36.71,0.0272,1.734,0.0268
18,basketball_ncaab,9957c1ba3bbf4571f8ae879f4c5f8191,Vanderbilt Commodores,McNeese Cowboys,2026-03-19 15:15:00-04:00,pinnacle,McNeese Cowboys,6.18,0.1618,3.901,0.1557
19,basketball_ncaab,9957c1ba3bbf4571f8ae879f4c5f8191,Vanderbilt Commodores,McNeese Cowboys,2026-03-19 15:15:00-04:00,pinnacle,Vanderbilt Commodores,1.14,0.8772,3.901,0.8443

## Kalshi Fn's

In [ ]:
x2 = k.kalshi_odds(x, .4)
display(x2)

Empty DataFrame
Columns: []
Index: []